sudo: false
language: node_js
node_js:
  - 0.10
  - 4.1
  - 4.2
services:
  - mongodb
addons:
  apt:
    sources:
      - mongodb-3.0-precise
    packages:
      - mongodb-org-server

before_install:
  - npm install -g grunt
  - npm install -g grunt-cli
  - gem install sass

script:
  - npm test

after_success:
  - ./node_modules/.bin/mocha --recursive --require blanket -R mocha-lcov-reporter | ./node_modules/coveralls/bin/coveralls.js
