sudo: false
language: node_js
node_js:
  - "0.10"
  - "0.12"
services:
  - mongodb

after_success:
  - ./node_modules/.bin/mocha --require blanket -R mocha-lcov-reporter | ./node_modules/coveralls/bin/coveralls.js
